name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: SimpliFile.AppImage
          path: dist/

      - name: Download macOS Artifact
        uses: actions/download-artifact@v4
        with:
          name: SimpliFile-macos.zip
          path: dist/

      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: SimpliFile-Windows.zip
          path: dist/

      - name: Create Git Tag
        id: create_tag
        shell: bash
        run: |
          TAG_NAME="v1.3.1-c$(git rev-list --count HEAD)"

          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          git tag $TAG_NAME
          git push origin $TAG_NAME

          echo "tag=$TAG_NAME" >> $GITHUB_OUTPUT
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.create_tag.outputs.tag }}
          files: |
            dist/SimpliFile.AppImage
            dist/SimpliFile-macos.zip
            dist/SimpliFile-Windows.zip
          body: |
            *This is an automated build, it may not be stable*

            **Builds by platform:**
            - Windows: SimpliFile-Windows.zip
            - Linux: SimpliFile.AppImage
            - macOS (both Intel & Apple Silicon): SimpliFile-macos.zip
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
